# Generated by Django 5.2.8 on 2025-12-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_mot_de_passe_hotel_date_ajout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
